"""Add address and order tables

Revision ID: 10343dfd7edc
Revises: 720327ba2efb
Create Date: 2025-09-23 14:54:41.893225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10343dfd7edc'
down_revision: Union[str, None] = '720327ba2efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.JSON(), nullable=False))
    op.add_column('orders', sa.Column('shipping_method', sa.JSON(), nullable=False))
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'shipping_info')
    op.drop_column('orders', 'buyer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_info', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'users', ['buyer_id'], ['id'])
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'user_id')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
