"""Align address model with frontend requirements

Revision ID: 1d0e62f87e8d
Revises: 76eac1fe9063
Create Date: 2025-09-30 15:03:53.356325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d0e62f87e8d'
down_revision: Union[str, None] = '76eac1fe9063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('addresses', sa.Column('province', sa.String(length=100), nullable=True))
    op.add_column('addresses', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('addresses', sa.Column('street_address_1', sa.String(length=500), nullable=False))
    op.add_column('addresses', sa.Column('street_address_2', sa.String(length=500), nullable=True))
    op.add_column('addresses', sa.Column('additional_info', sa.JSON(), nullable=True))
    op.alter_column('addresses', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('addresses', 'address_line_2')
    op.drop_column('addresses', 'address_line_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('address_line_1', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('addresses', sa.Column('address_line_2', mysql.VARCHAR(length=500), nullable=True))
    op.alter_column('addresses', 'phone_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('addresses', 'additional_info')
    op.drop_column('addresses', 'street_address_2')
    op.drop_column('addresses', 'street_address_1')
    op.drop_column('addresses', 'district')
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'country')
    # ### end Alembic commands ###
