"""product table update

Revision ID: 3c925a1db402
Revises: 6f07a003f3b1
Create Date: 2025-07-20 07:07:49.464514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c925a1db402'
down_revision: Union[str, None] = '6f07a003f3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'image_urls',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
    op.drop_column('products', 'is_favorite')
    op.drop_column('products', 'is_sold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_sold', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_favorite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('products', 'image_urls',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
    op.alter_column('products', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
