"""upgrade chatroom api

Revision ID: 463efb3fa570
Revises: baa1f780d692
Create Date: 2025-10-08 09:42:08.671674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '463efb3fa570'
down_revision: Union[str, None] = 'baa1f780d692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('chat_messages', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'is_read',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'is_read',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('chat_messages', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'image_url')
    # ### end Alembic commands ###
