"""Add quantity to wishpool

Revision ID: 5e441ebbc9e1
Revises: 0b25de3aab80
Create Date: 2025-12-08 14:29:24.090558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e441ebbc9e1'
down_revision: Union[str, None] = '0b25de3aab80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishpools', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('wishpools', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('wishpools', 'price_min')
    op.drop_column('wishpools', 'price_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishpools', sa.Column('price_max', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('wishpools', sa.Column('price_min', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('wishpools', 'quantity')
    op.drop_column('wishpools', 'price')
    # ### end Alembic commands ###
