"""update auth

Revision ID: 6f07a003f3b1
Revises: b694e93a0515
Create Date: 2025-07-03 22:44:14.543246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f07a003f3b1'
down_revision: Union[str, None] = 'b694e93a0515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=False))
    op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('sales_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_sold', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('shipping_info', sa.JSON(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    op.add_column('users', sa.Column('buyer_rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('code_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_expiration')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'buyer_rating')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('products', 'shipping_info')
    op.drop_column('products', 'seller_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_sold')
    op.drop_column('products', 'is_favorite')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'average_rating')
    op.drop_column('products', 'sales_count')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'image_urls')
    op.drop_column('products', 'status')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'category')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
