"""Add shipping_address to wishpool

Revision ID: 90d6ca8fd60d
Revises: 5e441ebbc9e1
Create Date: 2025-12-08 16:24:16.749573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d6ca8fd60d'
down_revision: Union[str, None] = '5e441ebbc9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishpools', sa.Column('shipping_address', sa.JSON(), nullable=False))
    op.add_column('wishpools', sa.Column('shipping_name', sa.String(length=100), nullable=False))
    op.add_column('wishpools', sa.Column('shipping_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishpools', 'shipping_cost')
    op.drop_column('wishpools', 'shipping_name')
    op.drop_column('wishpools', 'shipping_address')
    # ### end Alembic commands ###
