"""add chat_room and message

Revision ID: a66fb886027d
Revises: 1d0e62f87e8d
Create Date: 2025-10-01 12:25:21.539080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66fb886027d'
down_revision: Union[str, None] = '1d0e62f87e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_product_uc', 'wishlist_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_product_uc', 'wishlist_items', type_='unique')
    # ### end Alembic commands ###
