"""Initial migration

Revision ID: b694e93a0515
Revises: 
Create Date: 2025-06-23 03:31:46.159163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b694e93a0515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_seller', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seller_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('seller_description', mysql.LONGTEXT(), nullable=True))
    op.add_column('users', sa.Column('seller_rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('product_count', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'product_count')
    op.drop_column('users', 'seller_rating')
    op.drop_column('users', 'seller_description')
    op.drop_column('users', 'seller_name')
    op.drop_column('users', 'is_seller')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
